// src/lib/components/Footer.svelte
<script>
  import {Twitter, GitHub} from '$lib/components/icons';
</script>

<footer>
  <div class="max-width-container">
    <div class="social-container">
      <a href="https://twitter.com/tomhendra" target="_blank">
        <Twitter />
        <span class="visually-hidden">Link to Tom Hendra's Twitter Account</span
        >
      </a>
      <a href="https://github.com/tomhendra" target="_blank">
        <GitHub />
        <span class="visually-hidden">Link to Tom Hendra's GitHub Account</span>
      </a>
    </div>
    <a class="logo-container" href="/">
      <img src="/logo.svg" alt="Logo - Home" />
      <span>Tom Hendra</span>
    </a>
    <span>&copy; {new Date().getFullYear()} Tom Hendra</span>
  </div>
</footer>

<style lang="scss">
  footer {
    background-color: var(--gray-800);
    color: var(--gray-400);

    a {
      text-decoration: none;
      color: inherit;
    }
  }

  .max-width-container {
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    padding-top: var(--space-12);
    padding-bottom: var(--space-12);

    @include mobileAndDown {
      flex-direction: column;
      gap: var(--space-6);
    }
  }

  .social-container {
    display: flex;
    align-items: center;
    gap: var(--space-6);
  }

  .logo-container {
    display: flex;
    align-items: center;
    gap: var(--space-2);
    color: var(--gray-400);
    font-weight: var(--font-weight-semibold);

    img {
      width: var(--space-8);
    }

    @include mobileAndDown {
      order: -1;
      margin-bottom: var(--space-6);
    }
  }
</style>

// app/components/Footer/Footer.tsx
import type { LinksFunction } from "@remix-run/cloudflare";
import styles from "./Footer.css";
import TomhendraLogo, { links as tomhendraLogoStyles } from "../Logo";
import { GitHub, Twitter } from "react-feather";

export const links: LinksFunction = () => [
  { rel: "stylesheet", href: styles },
  ...tomhendraLogoStyles(),
];

export default function Footer() {
  return (
    <footer className="footer">
      <div className="footer-container u-max-width-container">
        <div className="social-container">
          <a
            href="https://twitter.com/tomhendra"
            target="_blank"
            rel="noreferrer"
          >
            <Twitter />
            <span className="u-visually-hidden">
              Link to Tom Hendra's Twitter Account
            </span>
          </a>
          <a
            href="https://github.com/tomhendra"
            target="_blank"
            rel="noreferrer"
          >
            <GitHub />
            <span className="u-visually-hidden">
              Link to Tom Hendra's GitHub Account
            </span>
          </a>
        </div>
        <a className="logo-container" href="/">
          <TomhendraLogo />
          <span className="wordmark">Tom Hendra</span>
          <span className="u-visually-hidden">Tom Hendra logo - Home</span>
        </a>
        <div className="copyright">
          <span className="copyright-text">
            &copy; {new Date().getFullYear()} Tom Hendra
          </span>
        </div>
      </div>
    </footer>
  );
}
